// Mocks generated by Mockito 5.4.4 from annotations
// in sensorlab/test/features/noise_meter/application/notifiers/enhanced_noise_meter_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sensorlab/src/features/noise_meter/domain/entities/acoustic_report_entity.dart'
    as _i5;
import 'package:sensorlab/src/features/noise_meter/domain/entities/noise_data.dart'
    as _i4;
import 'package:sensorlab/src/features/noise_meter/domain/repositories/acoustic_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AcousticRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAcousticRepository extends _i1.Mock
    implements _i2.AcousticRepository {
  MockAcousticRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.NoiseData> get noiseStream => (super.noSuchMethod(
        Invocation.getter(#noiseStream),
        returnValue: _i3.Stream<_i4.NoiseData>.empty(),
      ) as _i3.Stream<_i4.NoiseData>);

  @override
  _i3.Future<bool> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveReport(_i5.AcousticReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReport,
          [report],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.AcousticReport>> getReports() => (super.noSuchMethod(
        Invocation.method(
          #getReports,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.AcousticReport>>.value(<_i5.AcousticReport>[]),
      ) as _i3.Future<List<_i5.AcousticReport>>);

  @override
  _i3.Future<void> deleteReport(String? reportId) => (super.noSuchMethod(
        Invocation.method(
          #deleteReport,
          [reportId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllReports() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllReports,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
